name: Packages
runs:
  using: composite
  steps:
    - name: Setup Node v16
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        registry-url: "https://registry.npmjs.org"
    - name: Restore cache
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/*/node_modules
        # obviously we need to hash `yarn.lock` because that specifies all our
        # external dependencies, but we also need to hash all of our
        # `package.json` files because Yarn creates symlinks under
        # `node_modules/@penrose/` for each of our packages, so we need to
        # update those if any packages are added
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install packages
      run: yarn
      shell: bash
