name: Packages
runs:
  using: composite
  steps:
    - name: Install Wasm target
      run: rustup target add wasm32-unknown-unknown
      shell: bash
    - name: Install wasm-bindgen
      # as mentioned in CONTRIBUTING.md, we need the --keep-lld-exports flag,
      # which will be available in the next wasm-bindgen release, but for now
      # the latest release is 0.2.83 which does not have it, so we are using our
      # own Linux binary which we built and uploaded to a GitHub Gist
      run: |
        wget -P ~/.cargo/bin \
          https://gist.github.com/samestep/2cf703cfd81691f2cb3c23422fce7e56/raw/f27692e7269f798faaf259b9c75942b151d8b69b/wasm-bindgen
        chmod +x ~/.cargo/bin/wasm-bindgen
      shell: bash
    - name: Restore cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        # obviously we need to hash yarn.lock because that specifies all our
        # external dependencies, but we also need to hash package.json because
        # Yarn creates symlinks under node_modules/@penrose/ for each of our
        # packages, so we need to update those if any packages are added; note
        # that this strategy means we cannot use wildcards in the "packages"
        # list in package.json, and must instead list them all explicitly (just
        # as we must in penrose.code-workspace)
        key: ${{ runner.os }}-${{ hashFiles('package.json', 'yarn.lock') }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install packages
      run: yarn
      shell: bash
