FROM ubuntu
RUN mkdir -p /opt/penrose
WORKDIR /opt/penrose
RUN apt-get update && apt-get install -y \
  ca-certificates \
  libgmp-dev

ENTRYPOINT ["penrose"]
CMD ["src/sub/twosets.sub","src/sty/venn_comp.sty","src/dsll/setTheory.dsl"]