FROM fpco/stack-build:lts-9.10

RUN mkdir -p /opt/penrose
COPY . /opt/penrose/
WORKDIR /opt/penrose

ENTRYPOINT ["./penrose"]
EXPOSE 9160
CMD ["--domain=0.0.0.0","src/sty/venn.sty","src/set-theory-domain/setTheory.dsl"]
