name: Setup
runs:
  using: composite
  steps:
    - name: Restore lerna cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install packages
      run: yarn
      shell: bash
