// Generated by scripts/elementary-topology/sync-figure-modules.mjs.
// Unreviewed example programs are deliberately outside the reader build.
export const figurePrograms: Record<string, () => Promise<unknown>> = {
  "../../../bloom/dist/examples/baire-category.js": () =>
    import("../../../bloom/dist/examples/baire-category.js"),
  "../../../bloom/dist/examples/connectedness.js": () =>
    import("../../../bloom/dist/examples/connectedness.js"),
  "../../../bloom/dist/examples/contraction-iterates.js": () =>
    import("../../../bloom/dist/examples/contraction-iterates.js"),
  "../../../bloom/dist/examples/convergence.js": () =>
    import("../../../bloom/dist/examples/convergence.js"),
  "../../../bloom/dist/examples/countable-enumeration.js": () =>
    import("../../../bloom/dist/examples/countable-enumeration.js"),
  "../../../bloom/dist/examples/cover-loops.js": () =>
    import("../../../bloom/dist/examples/cover-loops.js"),
  "../../../bloom/dist/examples/derived-sets.js": () =>
    import("../../../bloom/dist/examples/derived-sets.js"),
  "../../../bloom/dist/examples/early-tables.js": () =>
    import("../../../bloom/dist/examples/early-tables.js"),
  "../../../bloom/dist/examples/group-kernels.js": () =>
    import("../../../bloom/dist/examples/group-kernels.js"),
  "../../../bloom/dist/examples/homotopies.js": () =>
    import("../../../bloom/dist/examples/homotopies.js"),
  "../../../bloom/dist/examples/homotopy-constructions.js": () =>
    import("../../../bloom/dist/examples/homotopy-constructions.js"),
  "../../../bloom/dist/examples/identification-sources.js": () =>
    import("../../../bloom/dist/examples/identification-sources.js"),
  "../../../bloom/dist/examples/loop-retracing.js": () =>
    import("../../../bloom/dist/examples/loop-retracing.js"),
  "../../../bloom/dist/examples/loops.js": () =>
    import("../../../bloom/dist/examples/loops.js"),
  "../../../bloom/dist/examples/metric-completeness.js": () =>
    import("../../../bloom/dist/examples/metric-completeness.js"),
  "../../../bloom/dist/examples/original-subspaces.js": () =>
    import("../../../bloom/dist/examples/original-subspaces.js"),
  "../../../bloom/dist/examples/point-set-topology.js": () =>
    import("../../../bloom/dist/examples/point-set-topology.js"),
  "../../../bloom/dist/examples/product-surfaces.js": () =>
    import("../../../bloom/dist/examples/product-surfaces.js"),
  "../../../bloom/dist/examples/product-topology.js": () =>
    import("../../../bloom/dist/examples/product-topology.js"),
  "../../../bloom/dist/examples/quotient-spaces.js": () =>
    import("../../../bloom/dist/examples/quotient-spaces.js"),
  "../../../bloom/dist/examples/topology-bases.js": () =>
    import("../../../bloom/dist/examples/topology-bases.js"),
  "../../../examples/dist/elementary-topology/bounded-sets.js": () =>
    import("../../../examples/dist/elementary-topology/bounded-sets.js"),
  "../../../examples/dist/elementary-topology/closed-interval.js": () =>
    import("../../../examples/dist/elementary-topology/closed-interval.js"),
  "../../../examples/dist/elementary-topology/connectedness-constructions.js":
    () =>
      import(
        "../../../examples/dist/elementary-topology/connectedness-constructions.js"
      ),
  "../../../examples/dist/elementary-topology/covering-properties.js": () =>
    import("../../../examples/dist/elementary-topology/covering-properties.js"),
  "../../../examples/dist/elementary-topology/dyadic-neighborhoods.js": () =>
    import(
      "../../../examples/dist/elementary-topology/dyadic-neighborhoods.js"
    ),
  "../../../examples/dist/elementary-topology/endpoint-identification.js": () =>
    import(
      "../../../examples/dist/elementary-topology/endpoint-identification.js"
    ),
  "../../../examples/dist/elementary-topology/function-neighborhoods.js": () =>
    import(
      "../../../examples/dist/elementary-topology/function-neighborhoods.js"
    ),
  "../../../examples/dist/elementary-topology/function-sequences.js": () =>
    import("../../../examples/dist/elementary-topology/function-sequences.js"),
  "../../../examples/dist/elementary-topology/fundamental-group-spaces.js":
    () =>
      import(
        "../../../examples/dist/elementary-topology/fundamental-group-spaces.js"
      ),
  "../../../examples/dist/elementary-topology/lebesgue-number.js": () =>
    import("../../../examples/dist/elementary-topology/lebesgue-number.js"),
  "../../../examples/dist/elementary-topology/limit-uniqueness.js": () =>
    import("../../../examples/dist/elementary-topology/limit-uniqueness.js"),
  "../../../examples/dist/elementary-topology/local-compactness.js": () =>
    import("../../../examples/dist/elementary-topology/local-compactness.js"),
  "../../../examples/dist/elementary-topology/lower-limit-topology.js": () =>
    import(
      "../../../examples/dist/elementary-topology/lower-limit-topology.js"
    ),
  "../../../examples/dist/elementary-topology/metric-comparison.js": () =>
    import("../../../examples/dist/elementary-topology/metric-comparison.js"),
  "../../../examples/dist/elementary-topology/metric-continuity.js": () =>
    import("../../../examples/dist/elementary-topology/metric-continuity.js"),
  "../../../examples/dist/elementary-topology/metric-neighborhoods.js": () =>
    import(
      "../../../examples/dist/elementary-topology/metric-neighborhoods.js"
    ),
  "../../../examples/dist/elementary-topology/neighborhood-inclusion.js": () =>
    import(
      "../../../examples/dist/elementary-topology/neighborhood-inclusion.js"
    ),
  "../../../examples/dist/elementary-topology/oscillating-sine-curve.js": () =>
    import(
      "../../../examples/dist/elementary-topology/oscillating-sine-curve.js"
    ),
  "../../../examples/dist/elementary-topology/path-extensions.js": () =>
    import("../../../examples/dist/elementary-topology/path-extensions.js"),
  "../../../examples/dist/elementary-topology/projection-preimage.js": () =>
    import("../../../examples/dist/elementary-topology/projection-preimage.js"),
  "../../../examples/dist/elementary-topology/separation-axioms.js": () =>
    import("../../../examples/dist/elementary-topology/separation-axioms.js"),
  "../../../examples/dist/elementary-topology/sequence-convergence.js": () =>
    import(
      "../../../examples/dist/elementary-topology/sequence-convergence.js"
    ),
  "../../../examples/dist/elementary-topology/topological-projections.js": () =>
    import(
      "../../../examples/dist/elementary-topology/topological-projections.js"
    ),
};
