VectorSpace U, V, W, X
LinearMap f, g, h
From(f,U,V)
From(g,V,W)
From(h,W,X)

Vector u1, u2, u3, u4, u5
In(u1,U)
In(u2,U)
In(u3,U)
In(u4,U)
In(u5,U)

Vector v1, v2, v3
In(v1,V)
In(v2,V)
In(v3,V)

u3 := AddV(u1,u2)

v1 := Apply(f,u1)
v2 := Apply(f,u2)
v3 := Apply(f,u3) = v1 + v2

-- the "equivalence" equal sign is tentative
Scalar a := Determinant(u1,u3)
u4 := a * u2
u5 := -u4
Scalar m := |v2| Scalar c := <v1, v3>
Vector w1 ∈ W := g(v1) Vector x1 ∈ X := h(w1)
