-- caffeine molecule, expressed via structural-formula DSL
Carbon C1, C2, C3, C4, C5, C6, C7, C8
Nitrogen N1, N2, N3, N4
Oxygen O1, O2
Hydrogen H1, H2, H3, H4, H5, H6, H7, H8, H9, H10

SingleBonded(N2, C4)
SingleBonded(C4, C5)
DoubleBonded(C5, C6)
SingleBonded(C6, N1)
SingleBonded(N1, C2)
SingleBonded(N2, C2)
DoubleBonded(C2, O2)
SingleBonded(N2, C1)
SingleBonded(C1, H7)
SingleBonded(C1, H6)
SingleBonded(C1, H5)
DoubleBonded(C4, O1)
SingleBonded(C7, H4)
SingleBonded(C7, H3)
SingleBonded(H2, C7)
SingleBonded(N3, C7)
SingleBonded(N3, C5)
SingleBonded(C8, N3)
DoubleBonded(C8, N4)
SingleBonded(N4, C6)
SingleBonded(C8, H1)
SingleBonded(C3, H10)
SingleBonded(C3, H8)
SingleBonded(C3, H9)
SingleBonded(N1, C3)

AutoLabel All
