-- caffeine molecule, expressed via structural-formula DSL
Carbon C2, C4, C5, C6, C8
Nitrogen N1, N2, N3, N4
Oxygen O1, O2
Hydrogen H1
FunctionalGroup methyl1, methyl2, methyl3

SingleBonded(methyl1, N2)
SingleBonded(N2, C4)
SingleBonded(C4, C5)
DoubleBonded(C5, C6)
SingleBonded(C6, N1)
SingleBonded(N1, C2)
SingleBonded(C2, N2)
DoubleBonded(C2, O2)
DoubleBonded(C4, O1)
SingleBonded(N3, methyl2)
SingleBonded(N3, C5)
SingleBonded(N3, C8)
DoubleBonded(C8, N4)
SingleBonded(N4, C6)
SingleBonded(C8, H1)
SingleBonded(N1, methyl3)

AutoLabel All
Label methyl1 $\mathrm{H}_3\mathrm{C}$
Label methyl2 $\mathrm{CH}_3$
Label methyl3 $\mathrm{CH}_3$

