-- glucose molecule, expressed via structural-formula DSL
Oxygen O1
Hydrogen H1, H2, H3, H4
Carbon C1, C2, C3, C4, C5
Molecule hydroxy_anion1, hydroxy_anion2, hydroxy_anion3
Molecule hydroxy_cation
Molecule hydroxy_methyl

SingleBonded(hydroxy_methyl, C1)
SingleBonded(C1, O1)
SingleBonded(C1, C2)
SingleBonded(C2, C3)
SingleBonded(C3, C4)
SingleBonded(C4, C5)
SingleBonded(C5, O1)
SingleBonded(C2, H1)
SingleBonded(C2, hydroxy_cation)
SingleBonded(C3, hydroxy_anion1)
SingleBonded(C3, H2)
SingleBonded(C4, H3)
SingleBonded(C4, hydroxy_anion2)
SingleBonded(C5, H4)
SingleBonded(C5, hydroxy_anion3)

AutoLabel All
Label hydroxy_cation $\mathrm{HO}$
Label hydroxy_anion1 $\mathrm{OH}$
Label hydroxy_anion2 $\mathrm{OH}$
Label hydroxy_anion3 $\mathrm{OH}$
Label hydroxy_methyl $\mathrm{CH}_2\mathrm{OH}$
