-- photosynthesis, expressed via structural-formula DSL
Carbon C1, C2, C3, C4, C5, C6

Oxygen O1, O2, O3, O4, O5, O6
Oxygen O7, O8, O9, O10, O11, O12
Oxygen O13, O14, O15, O16, O17, O18

Hydrogen H1, H2, H3, H4, H5, H6
Hydrogen H7, H8, H9, H10, H11, H12

-- water
SingleBond(O13, H1)
SingleBond(O13, H2)

-- water
SingleBond(O14, H3)
SingleBond(O14, H4)

-- water
SingleBond(O15, H5)
SingleBond(O15, H6)

-- water
SingleBond(O16, H7)
SingleBond(O16, H8)

-- water
SingleBond(O17, H9)
SingleBond(O17, H10)

-- water
SingleBond(O18, H11)
SingleBond(O18, H12)


-- carbon dioxide
DoubleBond(C1, O1)
DoubleBond(C1, O2)

-- carbon dioxide
DoubleBond(C2, O3)
DoubleBond(C2, O4)

-- carbon dioxide
DoubleBond(C3, O5)
DoubleBond(C3, O6)

-- carbon dioxide
DoubleBond(C4, O7)
DoubleBond(C4, O8)

-- carbon dioxide
DoubleBond(C5, O9)
DoubleBond(C5, O10)

-- carbon dioxide
DoubleBond(C6, O11)
DoubleBond(C6, O12)

AutoLabel All
