// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser, LocalTokenGroup } from "@lezer/lr";
import { insertSemicolon, trackNewline } from "./domainTokens.js";
const spec_Identifier = {
  __proto__: null,
  type: 12,
  predicate: 18,
  symmetric: 24,
  function: 28,
  constructor: 32,
};
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "'tQ`QPOOPtOPOOOyQPO'#CcOOQQ'#Cz'#CzO!OQRO'#CnQ`QPOOO!WQPO'#C`O!]QPO'#CdO!bQPO'#CgO!gQPO'#CiO!lQPO'#CkP!qOSO'#C^POOO)C>i)C>iO!|QPO,58}OOQO'#DS'#DSOOQO,59Y,59YOOQO-E6l-E6lO#RQRO,58zOOQQ,58z,58zO#^QPO,59OOOQQ,59R,59RO#^QPO,59TO#^QPO,59VPOOO'#Cm'#CmP#cOSO,58xPOOO,58x,58xO#nQRO'#C|OOQQ1G.i1G.iO#yQPO'#CfOOQQ1G.j1G.jO$RQPO1G.oO$WQRO1G.qPOOO-E6k-E6kPOOO1G.d1G.dO$cQPO'#CoO$hQRO,59hO$sQPO'#DQO%OQPO,59QO%TQPO7+$ZO%YQPO7+$]OOQQ,59Z,59ZOOQQ-E6m-E6mO%_QPO'#CpO%dQPO,59lO%dQPO,59lOOQQ1G.l1G.lOOQQ<<Gu<<GuOOQQ<<Gw<<GwO%lQPO,59[OOQO-E6n-E6nO%wQPO1G/WOOQO1G.v1G.v",
  stateData:
    "&P~OhOSiOSPOSjPQ~OTQOUUOXVO[WO^XO`YO~OjZO~Oo]O~Of^Ow^O~OTaO~OTcO~OXVO~OTeO~OTfO~OkgOlgOmiO~OTjO~Oo]OfSawSa~OslO~OkgOlgOmqO~OqrOfpXwpX~OTtOrtP~OuvO~OuwOf_iw_i~OTxO~OqrOfpawpa~OT|OqzOrtX~Or}O~OT!OO~OT!PO~OT!QO~OqzOrta~OT!TOqdarda~OqzOrti~O",
  goto: "#cwPPxP{PP!P!WP!_{P{P{P!h!n!t!zPPPPPPPPP#UP#YPPP#]P#`R[PTROTSROTRbUSROTRdWQmcQneRofQhZRphQTOR`TQsjRysQ{tS!R{!SR!S|TSOTRk]RulR_S",
  nodeNames:
    "⚠ LineComment BlockComment Program Type Identifier type Subtype Predicate predicate ParamList SymPred symmetric Function function Constructor constructor",
  maxTerm: 39,
  context: trackNewline,
  skippedNodes: [0, 1, 2, 17],
  repeatNodeCount: 4,
  tokenData:
    "$r~RaXY!WYZ!iZ[!W]^!ipq!Wxy!nyz!s|}!x}!O!}!P!Q#t!Q![$P!]!^$b!^!_$g!c!}$P#R#S$P#T#o$P$f$g!W~!]Sh~XY!WZ[!Wpq!W$f$g!W~!nOi~~!sOs~~!xOr~~!}Oq~~#QQ}!O#W!`!a#o~#]SP~OY#WZ;'S#W;'S;=`#i<%lO#W~#lP;=`<%l#W~#tOu~~#wPz{#z~$POj~~$UST~!Q![$P!c!}$P#R#S$P#T#o$P~$gOw~~$jP![!]$m~$rOo~",
  tokenizers: [
    1,
    insertSemicolon,
    new LocalTokenGroup("j~RQYZXz{^~^Ol~~aP!P!Qd~iOm~~", 25, 27),
  ],
  topRules: { Program: [0, 3] },
  specialized: [{ term: 5, get: (value) => spec_Identifier[value] || -1 }],
  tokenPrec: 0,
});
