-- (1)

-- Object A, B, C
-- C := tensor(A, B)

-- (2)

-- Object A
-- Object B
-- Morphism F := join(A, B)

-- (3)

-- Object A, B, C, D
-- C := tensor(A, B)
-- Morphism F := join(C, D)

-- AutoLabel All

------

-- (4)

Object A, B, C , D
Object E, F

Object ab := tensor(A, B)
Object abc := tensor(ab, C)
Morphism F2 := join(abc, D)

Object de := tensor(D, E)
Morphism G := join(de, F)

-- TODO: Might need a plugin. Is there any way to naturally state this in the math, anyway?
InputOf(A, F2)
InputOf(B, F2)
InputOf(C, F2)

InputOf(D, G)
InputOf(E, G)

NotInputOf(E, F2)

-- Not really needed
-- OutputOf(D, F2)
-- OutputOf(F, G)

-- Presumably you would generate these by analyzing the "chain"? What would be the right thing to state here?

AutoLabel All
Label F2 $F^2$
Label G $G$

-- Even this simple example freezes up when the Object initially intersects the Morphism
-- Anything more complicated makes things crash for me

------

-- Object A
-- Morphism F

-- AutoLabel All