FROM fpco/stack-build:lts-13.24

RUN echo 'alias runpenrose=""' >> ~/.bashrc

# Put runpenrose in PATH with default domain arg (to be docker compatible)
RUN echo '/root/.local/bin --domain=0.0.0.0 "$@"' > /usr/bin/penrose && \
    chmod +x /usr/bin/penrose

WORKDIR /home/penrose/src

EXPOSE 9160
