FROM node:11.10.1

WORKDIR /home/node

RUN npm config set prefix "/home/node/.npm-packages"

ENV PATH="=/home/node/.npm-packages/bin:${PATH}"

COPY ./penrose-web/package.json /home/node/penrose-web/package.json

WORKDIR /home/node/penrose-web

RUN npm install

ENV CHOKIDAR_USEPOLLING=true

ENTRYPOINT ["sh", "-c", "PORT=3500 npm start"]

EXPOSE 3500