name: Setup
inputs:
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    default: 1
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Restore lerna cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install packages
      run: yarn
