import { resample, stepState } from "API";
import * as React from "react";
import ButtonBar from "ui/ButtonBar";
import Canvas from "ui/Canvas";
import { converged } from "packets";
import Resample from "ui/icons/Resample";
import Logo from "ui/icons/Logo";
import styled from "styled-components";

const EmbedContainer = styled.div`
  position: relative;
  border-radius: 10px;
  border: 0.5px solid rgba(0, 0, 0, 0.2);
  box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2);
  overflow: hidden;
`;

const EmbedFooter = styled.div`
  font-family: "Open Sans", sans-serif;
  display: flex;
  overflow: hidden;
  justify-content: space-between;
  color: white;
  padding: 0 1em;
  font-weight: lighter;
  font-size: smaller;
  align-items: center;
  background-color: #40b4f7;
  border-radius: 0 0 9px 9px;
`;

interface IEmbedState {
  data: State;
}

class Embed extends React.Component<any, IEmbedState> {
  buttons: React.RefObject<ButtonBar>;
  canvas: React.RefObject<Canvas>;

  // NOTE: assume an initial state passed in upon mounting
  constructor(props: IEmbedState) {
    super(props);
    this.state = { data: props.data };
    this.canvas = React.createRef<Canvas>();
    this.buttons = React.createRef<ButtonBar>();
    // step until convergence
    this.step();
  }

  public onCanvasState = async (canvasState: State) => {
    // HACK: this will enable the "animation" that we normally expect
    await new Promise((r) => setTimeout(r, 1));
    this.setState({
      data: canvasState,
    });
    if (!converged(canvasState)) {
      this.step();
    }
  };

  public step = (): void => {
    const stepped = stepState(this.state.data!);
    void this.onCanvasState(stepped);
  };

  public resample = (): void => {
    const NUM_SAMPLES = 1;
    const oldState = this.state.data;
    if (oldState) {
      const resampled = resample(oldState, NUM_SAMPLES);
      void this.onCanvasState(resampled);
    }
  };

  public updateData = async (data: State) => {
    this.setState({ data: { ...data } });
    const stepped = stepState(data);
    void this.onCanvasState(stepped);
  };

  public render() {
    const { data } = this.state;
    return (
      <EmbedContainer>
        <Canvas data={data} updateData={this.updateData} lock={false} />
        <EmbedFooter>
          <Logo width={24} color={"white"} />
          <p>Generated by Penrose with 🍑.💦🍆🔥🏳️‍🌈</p>
          <div onClick={this.resample}>
            <Resample size={24} color={"white"} />
          </div>
        </EmbedFooter>
      </EmbedContainer>
    );
  }
}

export default Embed;
