import * as React from "react";
import Logo from "./icons/Logo";
import Resample from "./icons/Resample";
import "./Overlay.css";
// import Resample from "ui/icons/Resample";

interface IProps {
  // converged: boolean;
  // autostep: boolean;
  // initial: boolean;
  // showInspector: boolean;
  // toggleInspector?(): void;
  // downloadPDF?(): void;
  // downloadSVG?(): void;
  // downloadState?(): void;
  // autoStepToggle?(): void;
  // step(): void;
  resample(): void;
}

class Overlay extends React.Component<IProps> {
  public render() {
    const { resample, children } = this.props;
    return (
      <div style={{ position: "relative" }}>
        <div className="embed-container"></div>
        {children}
        <div className="embed-footer">
          <Logo width={24} color={"white"} />
          <p style={{ marginLeft: 10 }}>
            Generated by Penrose with 🍑.💦🍆🔥🏳️‍🌈
          </p>
          <div onClick={resample}>
            <Resample size={24} color={"white"} />
          </div>
        </div>
      </div>
    );
  }
}

export default Overlay;
