SComplex K

Edge e
InES(e, K)

SSubset S1
IsSubsetOf(S1, K)
S1 := Star(e)

Subcomplex A
IsSubsetOf(A, K)
A := Closure(S1)

Label A $Cl(St(e))$
AutoLabel e
AutoLabel K
AutoLabel S1

----------------

Subcomplex B
B := Closure(e)

SSubset S2
IsSubsetOf(S2, K) -- TODO: Should this be A or K? Or both?
S2 := Star(B)

AutoLabel B
Label S2 $St(Cl(e))$ -- TODO: remove these labels

----------------

SSubset S3
IsSubsetOf(S3, K)
S3 := SetMinus(A, S2)

Label S3 $Cl(St(e)) \setminus St(Cl(e))$