Definition Surjection(Map f, Set A, Set B):
    forall b : B | exists a : A | f(a) = b

/*
-- dup symbol 1
Set A
Set A

-- dup symbol 2
Set A, B, C
Set A = { a, b, c, d }

-- dup symbol 2
Set A, B, C
Set D = { a, b, c, d }
f: A -> B
f(a) = b

-- inval func
f: A -> E
f: E -> B

-- inval constrs
In

Point A
Point A, B, C
f(a) = b
f(c) = d
Subset A B
Intersect A B
NoIntersect A B
Set A = { a, b, c, d }
*/
