Set A, B, C, D, E, F, G
Set H, I, J, K, L

IsSubset(B, A)
IsSubset(C, A)
IsSubset(D, B)
IsSubset(E, B)
IsSubset(F, C)
IsSubset(G, C)

NotIntersecting(E, D)
NotIntersecting(F, G)
NotIntersecting(B, C)

IsSubset(H, A)
IsSubset(H, A)
IsSubset(I, A)
IsSubset(I, A)
IsSubset(J, H)
IsSubset(J, H)
IsSubset(K, I)
IsSubset(K, I)
IsSubset(L, H)
IsSubset(L, H)
NotIntersecting(H, I)
NotIntersecting(L, J)
NotIntersecting(B, I)
NotIntersecting(B, H)
NotIntersecting(C, I)
NotIntersecting(C, H)

AutoLabel All
