name: Publish Storybook
on:
  push:
    paths: ["packages/components/src/stories/**", "packages/components/src/**", 
    "packages/core/src/**"]
    branches:
      - main
defaults:
  run:
    working-directory: ./packages/components
jobs:
  Install-And-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore lerna cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn
      - name: Build core
        run: yarn build
        working-directory: ./packages/core
      - name: Build storybook
        run: yarn build-storybook
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/components/storybook-static
          target-folder: storybook
      - name: Add .nojekyll
        run: |
          mkdir extra
          touch extra/.nojekyll
      - name: Deploy .nojekyll
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/components/extra
          clean: false
